### ISSUE TITLE
Feature request: Add a link to the RSS feed to https://www.openthesaurus.de/userEvent/list

### ISSUE THREAD

**Issue by janschreiber** [danielnaber/openthesaurus#22]
Currently, if I want to subscribe to the RSS feed with the most recent changes to the OT data, I have to go to the About page in order to learn that this feature exists.
At the same time, the main page of OT has a link to the page https://www.openthesaurus.de/userEvent/list with a link text of "Daten-Änderungen".
I would like to suggest to add a link on the page https://www.openthesaurus.de/userEvent/list to https://www.openthesaurus.de/feed that says something similar to "Sie können die aktuellen Änderungen auch als RSS_Feed abonnieren."

**Comment by danielnaber** [comment]
Done

**Comment by janschreiber** [comment]
Thank you.
