### ISSUE TITLE
add descriptions to synsets

### ISSUE THREAD

**Issue by schlichtanders** [danielnaber/openthesaurus#23]
Dear openthesaurus-team,

it would be great to have a short text-description for each synset.
Could this be added to the corpus?

**Comment by danielnaber** [comment]
Technically that wouldn't be difficult. The question is: what exactly would that description be for? How long would it be? How useful would it be, as most synsets wouldn't have that description set for a long time (we have 37,000 synsets on openthesaurus.de).

**Comment by schlichtanders** [comment]
the motivation was that this is also available within the famous WordNet and was mentioned on the nltk book http://www.nltk.org/book/ch02.html (search for ``definition()``)

I thought one could use this to map word to synset by evaluating the respective context. A description/definition would provide an example context.

**Comment by danielnaber** [comment]
Examples can already be attached to the words, as done in e.g. https://www.openthesaurus.de/synonyme/edit/33333

**Comment by schlichtanders** [comment]
thank you very much, that looks like I wanted, however of course it would great to have examples for every single synset... there might be a good semi automatic way to extract examples from corpus... still a lot of work.

**Comment by danielnaber** [comment]
Closing, as examples can already be attached to words.
