### ISSUE TITLE
Add uppercase character(s) with French circonflexe to word characters

### ISSUE THREAD

**Issue by janschreiber** [danielnaber/openthesaurus#24]
When trying to add the phrase "Raison d'Être" to OT (capitalization recommended by Duden), I get this error:

> Die Eigenschaft [word] des Typs [class com.vionto.vithesaurus.Term] mit dem Wert [Raison d'Être] entspricht nicht dem vorgegebenen Muster [[ 0-9a-zA-ZöäüÖÄÜßëçèéêáàóòÈÉÁÀÓÒãñíîş\{\}\"\?\*=()\-\+/.,'_:<>;%‰°\!\[\]²³Œ€&#ūαΑβΒγΓδΔεΕζΖηΗθΘιΙκΚλΛμΜνΝξΞοΟπΠρΡσΣτΤυΥφΦχΧψΨωΩάΆέΈίΊήΉύΎϊϋΰΐœţ]+]

Seems to me that at least the character Ê should be added to the RegEx here.

**Comment by danielnaber** [comment]
Should work now.
