### ISSUE TITLE
Requests per minute limitation and Tor network

### ISSUE THREAD

**Issue by privacy-wolf** [danielnaber/openthesaurus#25]
Just coming by here by chance - and just one comment: I see there is a limit of one request per second which should be more that sufficient for most IP addresses. This might be an issue for a larger group sharing the same IP address.

One such case is users with a need of increased anonymity and who are relying on Tor (see torproject.org for some background). Everyone using Tor and accessing openthesaurus will have one of the Exit-nodes IP addresses assigned on the request. So my suggestion would be to allow these IP addresses a higher rater (in case this is needed at all; currently everything is working perfectly well). Still some rate limit is usefull for these IPs as well; just higher maybe.

The Tor Exit node IPs can easily checked for at: [https://check.torproject.org/cgi-bin/TorBulkExitList.py](https://check.torproject.org/cgi-bin/TorBulkExitList.py) which also links to a plain-text full list of IPs (V4 and V6).

Keep on with the great work - it's an awesome and indispensable tool to learn German!

**Comment by danielnaber** [comment]
As there are hundreds of exit nodes, I don't think there is a problem. Nobody has complained so far.

**Comment by danielnaber** [comment]
Closing, as I don't think there's an issue currently. Also, the limit only applies to the API and it's not 1 request per second, but 60 requests per minute.
