### ISSUE TITLE
Android App

### ISSUE THREAD

**Issue by FionaHagen** [danielnaber/openthesaurus#26]
Is there an [OpenThesaurus](https://www.openthesaurus.de/) [Android](https://www.android.com/) app from a third-party developer or do you plan to make one yourself @danielnaber? I would love to have that ☺️ 
By the way, thanks for your awesome work! 😘

**Comment by danielnaber** [comment]
There's https://play.google.com/store/apps/details?id=org.softcatala.corrector, but it has some limitations, like not working on Samsung devices. There are no plans to write another app.

**Comment by danielnaber** [comment]
There's https://play.google.com/store/apps/details?id=sfischer13.openthesaurus

**Comment by FionaHagen** [comment]
Thanks for the info @danielnaber and @sfischer13 for making [it](https://github.com/sfischer13/robot-openthesaurus) 😘
