### ISSUE TITLE
Upgrade to grails 3.3.1

### ISSUE THREAD

**Issue by PanderMusubi** [danielnaber/openthesaurus#27]
![badge](https://api.bountysource.com/badge/issue?issue_id=49810378)

Please upgrade application.properties to grails version 3.3.1, see also https://grails.org/download.html

**Comment by PanderMusubi** [comment]
Installing grails version 2.3.11 on Ubuntu 17.04 with Java 8 etc. does not work. Grails exists with return value 1 and a cleared terminal screen. Building with grails 3.3.1, which does run on this system, requires application.properties file to support that version too.

**Comment by PanderMusubi** [comment]
See also https://stackoverflow.com/questions/35711616/grails-clean-command-throwing-null-pointer-exception

**Comment by PanderMusubi** [comment]
Note to self: apparently the directory structure has to be refactored for Grails version 3.3.1. See also http://docs.grails.org/3.2.7/guide/upgrading.html Will try to do so. Hope core devs can help out by reviewing the PR.

**Comment by PanderMusubi** [comment]
I will commit a branch today with a first attempt but see that it will need some serious review and improvements by a Grails developer (which I am not). Hopefully, somebody could bring it to a next stage this weekend.

**Comment by PanderMusubi** [comment]
Please review this commit and improve on it https://github.com/PanderMusubi/openthesaurus/commit/ed54f072164fd2cebef51fe47df20b93f7c6e11b

@danielnaber, probably good to get this branch also in top-level repo so other people can work on it more easily.

**Comment by PanderMusubi** [comment]
In short, for upgrade needs to support latest stable version of Grails on Ubuntu 18.04, Ubuntu LTS and Debian 9.4. Grails may be installed from upstream and not from OS distribution repo.

**Comment by danielnaber** [comment]
Trying Grails 3.3.1 with your `grails331` branch, I get `Error Error initializing classpath: Could not get unknown property 'grails' for root project 'openthesaurus' of type org.gradle.api.Project. (Use --stacktrace to see the full trace)`. Any idea?

**Comment by PanderMusubi** [comment]
@danielnaber My branch was an attempt to upgrade. I hoped you could fix where the branch gets stuck. Since I'm lacking the needed Grails upgrade skills, a bounty has been added via https://www.bountysource.com/issues/49810378-upgrade-to-grails-3-3-1

**Comment by ryu0** [comment]
Is this still waiting for a resolution?

**Comment by PanderMusubi** [comment]
Yes, please. @danielnaber, you are not working on this now?

**Comment by danielnaber** [comment]
No, I'm not working on this.

**Comment by ryu0** [comment]
I'll take a look at this soon. I've been swamped.

**Comment by WtfJoke** [comment]
I've started working on it too, but had some compile issues and havent commited anything yet. 

I also looked at your branch @PanderMusubi and you did at least one critical mistake. 
You need to write build.gradle from scratch you cannot simply rename grails-app/conf/BuildConfig.groovy → build.gradle as its another format.

**Comment by PanderMusubi** [comment]
That is exactly where my very limited knowledge of Grails prevented me to continue and when it was time to call in the experts.

As far as the rules for the bounty, they go to the person which successfully solves this issue first. We cannot split it, as it is paid via BountySource. We do not want to disappoint one or both of you. So if you both want to work on it, perhaps better discuss this first. Of course, we want the best fix, without personal disappointment, but we also value an indepent review of the result.

**Comment by ryu0** [comment]
Upon reviewing the guide for upgrading from Grails 2.3.x, it appears that the plugins used by openthesaurus will need to upgraded first. There appears to be 8 distinct plugin references in the existing repository. Some of them appear to have already been ported to Grails 3, but several appear to be unmaintained, such as feeds and jquery. How do you want to handle these? The easiest solution might be to drop them, but I don't know what they actually do here.

**Comment by danielnaber** [comment]
jQuery is used in the front-end, but I see no need to use it as a plugin. feeds creates the Atom feed at https://www.openthesaurus.de/feed I think.

**Comment by ryu0** [comment]
Sounds like they're important to keep then. I'll see if I can port these plugins. Since some are unmaintained, where should their source go? Hm.

**Comment by danielnaber** [comment]
This is now done thanks to @kstuart.

**Comment by PanderMusubi** [comment]
Thanks! I will try to install it next days and figure out how he can collect the bounty.

**Comment by PanderMusubi** [comment]
Yes, I have been able to configure, build and deploy it with Grails 3.3.1 on Ubuntu 18.04. Thank you. @kstuart Let me know if you need help claiming the bounty.

**Comment by kstuart** [comment]
Hi @PanderMusubi, good to know it's working well.

Yes, now the work is complete and openthesaurus has been running on the main site for a while it would be great to get the bounty released, you'll need to accept the claim on [BountySource](https://www.bountysource.com/issues/49810378-upgrade-to-grails-3-3-1), **Stichting OpenTaal** Could you do the same?

Thanks!

**Comment by PanderMusubi** [comment]
Done
