### ISSUE TITLE
Which JDK version to use? Can not grails run-app due to several errors with several jdk versions?

### ISSUE THREAD

**Issue by heimtech** [danielnaber/openthesaurus#29]
Hi danielnaber,

i want to build your app with grails 2.3.11, but with JDK 8 (jdk1.8.0_101)  i get copy errors for copying non-root methods and with jdk 7 (jdk1.7.0_80) i get UnsupportedClassVersionError 

Unsupported major.minor version 52.0

Which Java Version are you using?

**Comment by danielnaber** [comment]
I use `1.8.0_121`

**Comment by PanderMusubi** [comment]
@heimtech, if you could help with https://github.com/danielnaber/openthesaurus/issues/27 would be very welcome.

@danielnaber, which JDK and version would you recommend for latest stable Ubuntu?

**Comment by danielnaber** [comment]
@PanderMusubi I suggest using the latest Java 8 from Oracle.

**Comment by heimtech** [comment]
Hi
@danielnaber 
Thank you for that info. Do you use 32bit or 64bit? JRE or JDK?

**Comment by danielnaber** [comment]
JDK
```
> java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

**Comment by PanderMusubi** [comment]
Any specific reasons why to use Oracle's JDK? Are there certain known issues?

**Comment by PanderMusubi** [comment]
@heimtech, may I ask for which language are you going to use OpenThesaurus?

**Comment by PanderMusubi** [comment]
@danielnaber I'm still curious what the issues are with OpenJDK. Do have some info on this?

**Comment by danielnaber** [comment]
We use Oracle Java 8 and it works. I don't know whether there are issues with OpenJDK.
