### ISSUE TITLE
Hunspell produces not expected spell suggestions

### ISSUE THREAD

**Issue by Telesto12** [danielnaber/openthesaurus#69]
$ cd core/dictionaries/de
$ echo gebärdensprache | hunspell -d de_DE_frami
Hunspell 1.7.0
& gebärdensprache 4 0: Gebärdensprache, -gebärdensprache, sprachgebundene, sprachgebunden
so it can be reproduced on the command line without libreoffice involved so its not an issue within LibreOffice code and is presumably due to the o rule of
gebärdensprache/ozm in the de_DE_frami.dic/aff, i.e. specific to the spelling dictionary itself

Same also present in Dutch dictionary (https://github.com/OpenTaal/opentaal-hunspell). Recent changes there might give some pointers.

**Comment by Telesto12** [comment]
See also: https://bugs.documentfoundation.org/show_bug.cgi?id=139319

**Comment by danielnaber** [comment]
Closing, as I'm not sure why this is in the OpenThesaurus repo.
